export const intermediateRes = [
	{"videos":[{
		id:"1",
		source: "Python.org",
		desc: "Introduction to python, uses and advantages over other languages",
		url: "https://docs.python.org/3.8/tutorial/appetite.html",
		rating: 4,
	},
	{
		id:"2",
		source: "Python.org",
		desc: "Introduction to python, uses and advantages over other languages",
		url: "https://docs.python.org/3.8/tutorial/appetite.html",
		rating: 4,
	},
	{
		id:"3",
		source: "Python.org",
		desc: "Introduction to python, uses and advantages over other languages",
		url: "https://docs.python.org/3.8/tutorial/appetite.html",
		rating: 4,
	},
	{
		id:"4",
		source: "Python.org",
		desc: "Introduction to python, uses and advantages over other languages",
		url: "https://docs.python.org/3.8/tutorial/appetite.html",
		rating: 4,
	},
	{
		id:"5",
		source: "Python.org",
		desc: "Introduction to python, uses and advantages over other languages",
		url: "https://docs.python.org/3.8/tutorial/appetite.html",
		rating: 4,
	}]},
	{"webpages":[{
		id:"1",
		source: "Python.org",
		desc: "Introduction to python, uses and advantages over other languages",
		url: "https://docs.python.org/3.8/tutorial/appetite.html",
		rating: 4,
	},
	{
		id:"2",
		source: "Python.org",
		desc: "Introduction to python, uses and advantages over other languages",
		url: "https://docs.python.org/3.8/tutorial/appetite.html",
		rating: 4,
	},
	{
		id:"3",
		source: "Python.org",
		desc: "Introduction to python, uses and advantages over other languages",
		url: "https://docs.python.org/3.8/tutorial/appetite.html",
		rating: 4,
	},
	{
		id:"4",
		source: "Python.org",
		desc: "Introduction to python, uses and advantages over other languages",
		url: "https://docs.python.org/3.8/tutorial/appetite.html",
		rating: 4,
	},
	{
		id:"5",
		source: "Python.org",
		desc: "Introduction to python, uses and advantages over other languages",
		url: "https://docs.python.org/3.8/tutorial/appetite.html",
		rating: 4,
	}]},
	{"ebooks":[{
		id:"1",
		source: "Python.org",
		desc: "Introduction to python, uses and advantages over other languages",
		url: "https://docs.python.org/3.8/tutorial/appetite.html",
		rating: 4,
	},
	{
		id:"2",
		source: "Python.org",
		desc: "Introduction to python, uses and advantages over other languages",
		url: "https://docs.python.org/3.8/tutorial/appetite.html",
		rating: 4,
	},
	{
		id:"3",
		source: "Python.org",
		desc: "Introduction to python, uses and advantages over other languages",
		url: "https://docs.python.org/3.8/tutorial/appetite.html",
		rating: 4,
	},
	{
		id:"4",
		source: "Python.org",
		desc: "Introduction to python, uses and advantages over other languages",
		url: "https://docs.python.org/3.8/tutorial/appetite.html",
		rating: 4,
	},
	{
		id:"5",
		source: "Python.org",
		desc: "Introduction to python, uses and advantages over other languages",
		url: "https://docs.python.org/3.8/tutorial/appetite.html",
		rating: 4,
	}]}

]